# development:
#   dialect: mysql
#   datasource: ${DB_USERNAME}:${DB_PASSWORD}@/${DB_NAME}?parseTime=true
#   dir: database/migrations
#   table: migrations

# seed:
#   dialect: mysql
#   datasource: ${DB_USERNAME}:${DB_PASSWORD}@/${DB_NAME}?parseTime=true
#   dir: database/seeds
#   table: seeds

development:
  dialect: postgres
  datasource: host=${DB_HOST} dbname=${DB_NAME} user=${DB_USERNAME} password=${DB_PASSWORD} sslmode=disable
  dir: database/migrations
  table: migrations